In [1]:
list = [1,2,3,4]

In [2]:
list



[1, 2, 3, 4]

In [4]:
import numpy as np

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [8]:
twodlist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
twodlist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr2d = np.array(twodlist)

In [11]:
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
for i in range(0,5):
     print(i)

0
1
2
3
4


In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.44129472, 0.32229424, 0.28461157, 0.60435252, 0.93430064])

In [30]:
np.random.rand(5,5)

array([[0.56242099, 0.24547244, 0.65338028, 0.9336346 , 0.6136065 ],
       [0.73161888, 0.57432997, 0.30465555, 0.71801756, 0.40186975],
       [0.7581591 , 0.62250748, 0.64079826, 0.14980235, 0.9021197 ],
       [0.74546338, 0.88310562, 0.66425472, 0.64781024, 0.33714761],
       [0.16250889, 0.87650983, 0.30892488, 0.29545017, 0.46745061]])

In [31]:
np.random.randn(4)

array([ 0.24537524,  0.71039633, -1.51139844,  0.35141986])

In [32]:
# get the random number from standard deviation

In [33]:
np.random.randint(1,100)

62

In [34]:
np.random.randint(1,100,10)

array([94,  6, 18, 41,  2, 27, 38, 55,  1, 33])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
ranarr

array([ 6, 20,  2, 42, 40, 19,  1,  2, 23, 38])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
# reshape will only work if your have match element with the new shape/

In [42]:
ranarr.max()

42

In [43]:
ranarr.min()

1

In [44]:
ranarr.argmax()

3

In [45]:
#argmax will return the index of the array of the max data

In [47]:
ranarr

array([ 6, 20,  2, 42, 40, 19,  1,  2, 23, 38])

In [49]:
arr.shape

(25,)

In [50]:
arr2d = arr.reshape(5,5)

In [51]:
arr2d.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [ ]:
arr = np.arange()